# Generated by Django 4.1.4 on 2022-12-27 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_name', models.CharField(help_text='word name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='word created time added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='word name updated time')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='user first name', max_length=100)),
                ('last_name', models.CharField(help_text='user last name', max_length=100)),
                ('phone', models.IntegerField(default=False)),
                ('date_of_birth', models.DateField()),
                ('user', models.OneToOneField(help_text='user name', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meanings', models.CharField(help_text='meanings of words', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='word meaning created time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='word meaning updated time')),
                ('word_name', models.ForeignKey(help_text='Word name for meaning', on_delete=django.db.models.deletion.CASCADE, to='dictionary.word')),
            ],
        ),
    ]
