# Generated by Django 4.1.4 on 2022-12-27 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meaning',
            old_name='updated_time',
            new_name='updated_at',
        ),
    ]
