# Generated by Django 4.1.4 on 2022-12-28 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='meaning',
            table='meanings',
        ),
        migrations.AlterModelTable(
            name='word',
            table='words',
        ),
    ]
