# Generated by Django 4.1.4 on 2022-12-29 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_alter_meaning_table_alter_word_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='meaning',
            table=None,
        ),
    ]
